version: '3.8'

services:
  backend:
    container_name: processos
    build: .
    ports: 
      - 3050:3050
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules

volumes: 
  node_modules: