name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      DATABASE_URL: postgres://oraculo:oraculo123@localhost:5431/oraculo
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn run db:up
      - run: docker ps
      - run: yarn
      - run: yarn run db:migrate
      - run: yarn run db:seeders
      - run: yarn run test
        
      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y-%H-%M')"

      - name: Create JSON
        run: curl -X POST 'https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2021.1-Oraculo-Registros&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500' > fga-eps-mds-2021_1-Oraculo-Registros-${{ steps.date.outputs.date }}.json
        
      - name: Make release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fga-eps-mds-2021_1-Oraculo-Registros-${{ steps.date.outputs.date }}.json
      - name: Pushes sonar file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: fga-eps-mds-2021_1-Oraculo-Registros-${{ steps.date.outputs.date }}.json
          destination_repo: "fga-eps-mds/2021.1-Oraculo"
          destination_branch: "master"
          destination_folder: "analytics-raw-data"
          user_email: ${{ secrets.USER_EMAIL }}
          user_name: ${{ secrets.USER_NAME }}
          commit_message: 'Adding SonarCloud file - fga-eps-mds-2021_1-Oraculo-Registros-${{ steps.date.outputs.date }}.json'
