on: [push, pull_request]

name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://oraculo:oraculo123@localhost:5431/oraculo
      DB_HOST: localhost
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose up -d --build banco
      - run: docker ps
      - run: yarn
      - run: yarn run db:migrate
        env:
          DB_PORT: 5431
      - run: yarn run test
        env:
          DB_PORT: 5431

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
